# Generated by Django 4.1 on 2022-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
